name: Flutter Tests

on:
  # Run the workflow on pull requests and pushes to the main branch
  pull_request:
  push:
    branches:
      - '*'

jobs:
  flutter-test:
    runs-on: ubuntu-latest
    
    steps:
      # Check out the repository code
      - name: Check out code
        uses: actions/checkout@v3
        
      # Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest'
      
      # Get Flutter dependencies
      - name: Install dependencies
        run: flutter pub get
      
      # Run Flutter tests
      - name: Run tests
        run: flutter test
